allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "esbuild"
  - "sharp"
patchedDependencies:
  "@material/material-color-utilities@0.4.0": "patches/@material__material-color-utilities@0.4.0.patch"
