/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./../.vitepress/theme/components/BackToTop.vue')['default']
    Container: typeof import('./../.vitepress/theme/components/Container.vue')['default']
    ListReleases: typeof import('./../.vitepress/theme/components/ListReleases.vue')['default']
    UnoCSSIndicator: typeof import('./../.vitepress/theme/components/UnoCSSIndicator.vue')['default']
  }
}
