/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./../.vitepress/theme/components/BackToTop.vue')['default']
    MDYAppBarLink: typeof import('./../.vitepress/theme/components/MDYAppBarLink.vue')['default']
    MDYAppearance: typeof import('./../.vitepress/theme/components/MDYAppearance.vue')['default']
    MDYContent: typeof import('./../.vitepress/theme/components/MDYContent.vue')['default']
    MDYDoc: typeof import('./../.vitepress/theme/components/MDYDoc.vue')['default']
    MDYDocFooter: typeof import('./../.vitepress/theme/components/MDYDocFooter.vue')['default']
    MDYFooter: typeof import('./../.vitepress/theme/components/MDYFooter.vue')['default']
    MDYHome: typeof import('./../.vitepress/theme/components/MDYHome.vue')['default']
    MDYHomeHero: typeof import('./../.vitepress/theme/components/MDYHomeHero.vue')['default']
    MDYLanguage: typeof import('./../.vitepress/theme/components/MDYLanguage.vue')['default']
    MDYLayout: typeof import('./../.vitepress/theme/components/MDYLayout.vue')['default']
    MDYNav: typeof import('./../.vitepress/theme/components/MDYNav.vue')['default']
    MDYNavItem: typeof import('./../.vitepress/theme/components/MDYNavItem.vue')['default']
    MDYSocialLinks: typeof import('./../.vitepress/theme/components/MDYSocialLinks.vue')['default']
    MDYThemeProvider: typeof import('./../.vitepress/theme/components/MDYThemeProvider.vue')['default']
    UnoCSSIndicator: typeof import('./../.vitepress/theme/components/UnoCSSIndicator.vue')['default']
  }
}
